version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - pwd
      - ls -la
      - find . -name "package.json"
      - npm install
  build:
    commands:
      - echo Building the application...
      - echo No compilation needed for static HTML
      - npm run build  # if you have a build script
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: myapp-$CODEBUILD_START_TIME
